export enum RabbitMQ {
  CatalogQueue = 'catalog',
  AuthorizationQueue = 'authorization',
  CartQueue = 'cart',
  PaymentQueue = 'payment',
}

export enum ProductMSG {
  CREATE = 'CREATE_PRODUCT',
  FIND_ALL = 'FIND_PRODUCTS',
  FIND_ONE = 'FIND_PRODUCT',
  UPDATE = 'UPDATE_PRODUCT',
  DELETE = 'DELETE_PRODUCT',
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_STOCK_ITEMS = 'GET_STOCK_ITEMS_FROM_PRODUCT',
  ADD_CATEGORY = 'ADD_CATEGORY',
  REMOVE_CATEGORY = 'REMOVE_CATEGORY',
  PURCHASE = 'PURCHASE',
}

export enum BranchMSG {
  CREATE = 'CREATE_BRANCH',
  FIND_ALL = 'FIND_BRANCHES',
  FIND_ONE = 'FIND_BRANCH',
  UPDATE = 'UPDATE_BRANCH',
  DELETE = 'DELETE_BRANCH',
  GET_STOCK_ITEMS = 'GET_STOCK_ITEMS_FROM_BRANCH',
}

export enum CategoryMSG {
  CREATE = 'CREATE_CATEGORY',
  FIND_ALL = 'FIND_CATEGORIES',
  FIND_ONE = 'FIND_CATEGORY',
  UPDATE = 'UPDATE_CATEGORY',
  DELETE = 'DELETE_CATEGORY',
  GET_PRODUCTS = 'GET_PRODUCTS',
  ADD_PRODUCT = 'ADD_PRODUCT',
  REMOVE_PRODUCT = 'REMOVE_PRODUCT',
}

export enum StockItemMSG {
  CREATE = 'CREATE_STOCKITEM',
  FIND_ALL = 'FIND_STOCKITEMS',
  FIND_ONE = 'FIND_STOCKITEM',
  UPDATE = 'UPDATE_STOCKITEM',
  DELETE = 'DELETE_STOCKITEM',
  GET_BRANCH = 'GET_BRANCH',
  GET_PRODUCT = 'GET_PRODUCT',
}

export enum UserMSG {
  CREATE = 'CREATE_USER',
  FIND_ALL = 'FIND_USERS',
  FIND_ONE = 'FIND_USER',
  UPDATE = 'UPDATE_USER',
  DELETE = 'DELETE_USER',
  JWT = 'UPDATE_JWT',
}

export enum PaymentMSG {
  TRANSACTION = 'TRANSACTION',
  CONFIRM_PAYMENT = 'CONFIRM_PAYMENT',
}
